### ISSUE TITLE
jesus

### ISSUE THREAD

**Issue by magicalnoob** [funyeatsalad/holy-parser#7]
![image](https://user-images.githubusercontent.com/61070617/114472499-2c4cb380-9ba7-11eb-906b-9e55bd197016.png)

**Comment by funyeatsalad** [comment]
i met him in cod bo 3 too :DD

**Comment by magicalnoob** [comment]
![image](https://user-images.githubusercontent.com/61070617/114472616-6ddd5e80-9ba7-11eb-8429-ea24711913f3.png)
how to make octree

**Comment by magicalnoob** [comment]
good for oct tree
